language: minimal
os: linux

dist: bionic

addons:
  apt:
    packages:
      - texlive-latex-extra # Should pull everything as dependency
      - texlive-fonts-recommended
      - texlive-plain-generic

script:
  - cd VS-UtCS-Manual
  - make -f Makefile.live

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1361517953461007f39a  # community room
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
